posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

posts/routes.py
from datetime import datetime
from flask import render_template, url_for, flash, redirect, request, abort, jsonify, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Books
from flaskblog.posts.forms import PostForm
import requests

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('new_post.html', title="New Post", legend="New Post", form=form)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new_post.html', title=post.title, legend="Update Post", form=form)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'danger')
    return redirect(url_for('main.home'))


@posts.route("/search")
@login_required
def search():
    return render_template('search.html', title='Search')


@posts.route("/results", methods=['POST', 'GET'])
@login_required
def results():
    category = request.form.get('category')
    search = request.form.get('search')
    search = "'%" + search + "%'"
    results = db.session.execute("SELECT * FROM Books WHERE " + category + " LIKE " + search).fetchall()
    if db.session.execute("SELECT * FROM Books WHERE " + category + " LIKE " + search).rowcount == 0:
        message = 'We are sorry. There were no results for your search.'
        return render_template("results.html", message=message, results=results, title='Search Results')

    return render_template("results.html", results=results, title='Search Results')


@posts.route("/<string:book_num>", methods=['POST', 'GET'])
@login_required
def book(book_num):
    if db.session.execute("SELECT * FROM books WHERE book_num = :book_num", {"book_num": book_num}).rowcount == 0:
        return render_template("errors/404.html"), 404
    else:
        book = db.session.execute("SELECT * FROM books WHERE book_num = :book_num", {"book_num": book_num}).fetchone()

    posts = Post.query.filter_by(book_num=book_num).all()

    # Get APIs from Goodreads.
    res = requests.get("https://www.goodreads.com/book/review_counts.json", params={"key": "9p5DL4xMYjGwUyWDLfgDw", "isbns": book_num})
    if res.status_code != 200:
        raise Exception("ERROR: API request unsuccessful for.")
    data = res.json()
    num_ratings = data["books"][0]["work_ratings_count"]
    avg_rating = data["books"][0]["average_rating"]
    our_avg_rate = db.session.execute("SELECT AVG(Cast(rating as Float)) FROM post WHERE book_num = :book_num",
                                      {"book_num": book_num}).fetchone()[0]
    # Post a User's Review.
    form = PostForm()
    if form.validate_on_submit():
        rating = int(request.form.get("rating"))
        post1 = Post(title=form.title.data, content=form.content.data, author=current_user, book_num=book_num, rating=rating)
        db.session.add(post1)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template("book.html", title=book.name, book=book, posts=posts, form=form,
                           legend="Write a Review", num_ratings=num_ratings, avg_rating=avg_rating,
                           our_avg_rate=our_avg_rate)


@posts.route("/api/books/<string:book_num>")
def book_api(book_num):
    book = db.session.execute("SELECT * FROM books WHERE book_num = :book_num",
                              {"book_num": book_num}).fetchone()
    if book is None:
        return jsonify({"error": "Invalid isbn number"}), 422

    review_counts = db.session.execute("SELECT COUNT(rating) FROM post WHERE book_num = :book_num",
                                       {"book_num": book_num}).fetchone()[0]
    our_avg_rate = db.session.execute("SELECT AVG(Cast(rating as Float)) FROM post WHERE book_num = :book_num",
                                      {"book_num": book_num}).fetchone()[0]
    return jsonify({
        "title": book.name,
        "author": book.author,
        "year": book.year,
        "isbn": book.book_num,
        "review_count": review_counts,
        "average_score": our_avg_rate
    })

users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login failed. Check email and password', 'danger')
    return render_template('login.html', title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title="Account", image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(user_id=user.id).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user, title=f'{user.username} Posts')


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'success')
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash('Your password has been changed! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

templates/book.html
{% extends "layout.html" %}
{% block content %}
    <div class="card1">
        <h2 class="border-bottom mb-4">Book Details:</h2>
        <h3 class="border-bottom mb-2">{{ book.name }}</h3>
        <h6>Author: {{ book.author }}</h6>

        <section style="color:black; font-weight:bold;">
            <h6>Our users ranked that book: {{ our_avg_rate }}</h6>
            <p>Publication Year: {{ book.year }}</br>ISBN number: {{ book.book_num }}</br>
            Avg. Rating by Goodreads: {{ avg_rating }}</br>
            Total: {{ num_ratings }} votes.</p>
        </section>
        <section>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group">
                        {{ form.title.label(class="form-control-label") }}

                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class="form-control-label") }}

                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    <label for="sel">Rate the Book:</label>
                    <select class="form-control" id="sel" name="rating">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-dark") }}
                    </div>
            </form>
        </section>
        {% if posts %}
            <h4 class="border-bottom mb-2">Reviews by Others</h4>
            {% for post in posts %}
                <div class="media posts-main">
                    <img class="rounded-circle account-img" src="{{ url_for('static', filename= 'profile_pics/' + post.author.image_file) }}">
                    <div class="media-body article-header">
                        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></br>
                        <small class="text-muted">  Date: {{ post.date_posted.strftime('%d/%m/%Y') }}</small></br>
                        <h3><a href="{{ url_for('posts.post', post_id=post.id)}}" class="links-custom">{{ post.title }}</a></h3>
                        <a class="mr-2" href="{{ url_for('posts.book', book_num=post.book.book_num) }}">  Book: {{ post.book.name }}</a></br>
                        {% if post.rating %}
                          Book's Rank: <span class="mr-2">{{ post.rating }}/5</span></br>
                        {% else %}
                            Book's Rank: None</br>
                        {% endif %}


                       <p style="color: black;">{{ post.content }}</p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock content %}

templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <div class="media posts-main">
            <img class="rounded-circle account-img" src="{{ url_for('static', filename= 'profile_pics/' + post.author.image_file) }}">
            <div class="media-body article-header">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></br>
                <small class="text-muted">  Date: {{ post.date_posted.strftime('%d/%m/%Y') }}</small></br>
                <h3><a href="{{ url_for('posts.post', post_id=post.id)}}" class="links-custom">{{ post.title }}</a></h3>

                {% if post.book.name %}
                  Book: <a class="mr-2" href="{{ url_for('posts.book', book_num=post.book.book_num) }}">{{ post.book.name }}</a></br>
                {% else %}
                    Book: None</br>
                {% endif %}

                {% if post.rating %}
                  Book's Rank: <span class="mr-2">{{ post.rating }}/5</span></br>
                {% else %}
                    Book's Rank: None</br>
                {% endif %}

               </br><p style="color: black;">{{ post.content }}</p>
            </div>
        </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <button class="btn btn-outline btn-dark mb-4">{{ page_num }}</button>
            {% else %}
                <a class="btn mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        {% if title %}
            <title>Books Reviews Website - {{ title }}</title>
        {% else %}
            <title>Books Reviews Website</title>
        {% endif %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    </head>

    <body>
        <!--The Title of the page "Book Reviews" -->
        <header>
			<h1><a href="{{ url_for('main.home') }}" style="text-decoration:none;font-weight:bold;color:#9e2796;">Books Reviews Website</a></h1>
			<h4>some slogan here</h4>
        </header>
       <!--Navigation Bar-->
        <nav class="row clearfix">
            <div class="col-2">
            </div>
            <div class="col-6">
    			<a href="{{ url_for('main.home') }}">Home</a>
    			<a href="#">Reviews</a>
    			<a href="#">Contact</a>
    			<a href="{{ url_for('posts.search') }}">Search</a>
            </div>
        </nav>
        <div class="row">
            <div class="col-lg-2">
            </div>
            <div class="col-lg-6">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock content %}
            </div>
            <div class="col-lg-2">
                <div class="card1">
                    {% if current_user.is_authenticated %}
                        <h4 class="shadow-sm p-2 mb-3 bg-white rounded" style="text-align: center;">Wellcome</h4>
                        <ul class="list-group">
                            <li class="list-group-item" style="text-align: center; font-weight:bold;"><a href="{{ url_for('users.account') }}" class="links-custom">Account</a></li>
                            <li class="list-group-item" style="text-align: center;font-weight:bold;"><a href="{{ url_for('users.logout') }}" class="links-custom">Logout</a></li>
                        </ul>
                    {% else %}
                        <h4 class="shadow-sm p-2 mb-3 bg-white rounded" style="text-align: center;">Hello, Guest</h4>
                        <ul class="list-group">
                            <li class="list-group-item" style="text-align: center;font-weight:bold;"><a href="{{ url_for('users.login') }}" class="links-custom">Login</a></li>
                            <li class="list-group-item" style="text-align: center;font-weight:bold;"><a href="{{ url_for('users.register') }}" class="links-custom">Register</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-2">
            </div>
        </div>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="card1">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-dark") }}
                </div>
                <small class="text-muted ml-2"><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a></small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register Now!</a>
        </small>
    </div>
{% endblock content %}

templates/new_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="card1">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}

                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}

                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-dark") }}
                </div>
        </form>
    </div>
{% endblock content %}

templates/post.html
{% extends "layout.html" %}
{% block content %}
    <div class="media posts-main">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename= 'profile_pics/' + post.author.image_file) }}">
        <div class="media-body article-header">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></br>
            <small class="text-muted">  Date: {{ post.date_posted.strftime('%d/%m/%Y') }}</small></br>
                {% if post.book.name %}
                  Book: <a class="mr-2" href="{{ url_for('posts.book', book_num=post.book.book_num) }}">{{ post.book.name }}</a></br>
                {% else %}
                    Book: None</br>
                {% endif %}

                {% if post.rating %}
                  Book's Rank: <span class="mr-2">{{ post.rating }}/5</span></br>
                {% else %}
                    Book's Rank: None</br>
                {% endif %}
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mr-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete
                    </button>
                </div>
            {% endif %}
            <h3>{{ post.title }}</h3>
           <p style="color: black;">{{ post.content }}</p>
        </div>
            <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete the post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
              </div>
            </div>
          </div>
        </div>
    </div>

{% endblock content %}

templates/results.html
{% extends "layout.html" %}
{% block content %}
    <div class="card1">
        <h2 class="border-bottom mb-4">Search Results:</h2>
        {% if results %}
            <div class="list-group">
            {% for result in results %}
                    <a href="{{ url_for('posts.book', book_num=result.book_num) }}" class="list-group-item list-group-item-action"><h6>{{ result.name }}</h6>
                    <p>Author: {{ result.author }}</p></a>

            {% endfor %}
            </div>
            <p>{{ message }}</p>
        {% endif %}
    </div>


{% endblock content %}

templates/search.html
{% extends "layout.html" %}
{% block content %}
    <div class="card1">
        <form action="{{ url_for('posts.results') }}" method="post">
            <div class="form-group">
                <legend class="border-bottom mb-4">Search For a Book</legend>
                <select class="form-control" name="category">
                    <option value="name">Title</option>
                    <option value="author">Author</option>
                    <option value="book_num">ISBN</option>
                </select>
            </div>
            <div class="form-group">
                <input class="form-control" name="search" placeholder="Type your search...">
            </div>
            <div class="form-group">
                <button class="btn btn-secondary">Search</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="shadow-sm p-2 mb-3 bg-white rounded">Posts by {{ user.username }} <span class="badge badge-secondary">{{ posts.total }}</span></h2>
  {% for post in posts.items %}
    <div class="media posts-main">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename= 'profile_pics/' + post.author.image_file) }}">
        <div class="media-body article-header">
            <a class="mr-2" href="#">{{ post.author.username }}</a></br>
            <small class="text-muted">  Date: {{ post.date_posted.strftime('%d/%m/%Y') }}</small></br>
            <h3>{{ post.title }}</h3>
                {% if post.book.name %}
                  Book: <a class="mr-2" href="{{ url_for('posts.book', book_num=post.book.book_num) }}">{{ post.book.name }}</a></br>
                {% else %}
                    Book: None</br>
                {% endif %}

                {% if post.rating %}
                  Book's Rank: <span class="mr-2">{{ post.rating }}/5</span></br>
                {% else %}
                    Book's Rank: None</br>
                {% endif %}
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mr-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete
                    </button>
                </div>
            {% endif %}

           <p style="color: black;">{{ post.content }}</p>
        </div>
            <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete the post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
              </div>
            </div>
          </div>
        </div>
    </div>
  {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
          {% if posts.page == page_num %}
              <button class="btn btn-outline btn-dark mb-4">{{ page_num }}</button>
          {% else %}
              <a class="btn mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
          {% endif %}
      {% else %}
          ...
      {% endif %}
    {% endfor %}
{% endblock content %}